brand_name:
  default: ''
website_url:
  default: ''
logo_url:
  default: ''
mobile_logo_url:
  default: ''
always_display_links_in_mobile:
  default: false
links:
  type: list
  default: ''
icons:
  type: list
  default: ''
custom_font_awesome_icons:
  type: list
  default: ''
